language: python

os:
  - linux
  - osx

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.3  CONDA_PY=33
    - python=3.4  CONDA_PY=34
    - python=3.5  CONDA_PY=35
    - CONDA_NPY=18
    - CONDA_NPY=19
    - CONDA_NPY=110
  global:
    - secure: "H9PRFgMppmGPFeNPZ4WsYYUmRrGX/BZPUKlLzHlVyJ4AO6mvp3BzTouRjM93lLJCl/N+0EHvLuOl7LrS34VO5CNipFtLhhOs8r1PmppkmIYMzymcFEvJXq3rVq/tcr2MDWNmjB28qkojyv9DWh5tptvBkoUgSGkFuWftIFNv3Hamgr/TZVOuMDX3q3ZxeobUAeB63/DWLDrWq96lZIdHP6IJdLtJB3NDedh1QnT/m/X8Ko/daeFty87M1GzYlPL/F5JDaBNSdYscayBfch7n1x/hKQNHlCluZKE9fRtUJPrh+sWm2BzZ4ReGN6WjIL3UA4Mndal0de+zfqMIifNwnZdLaqZ8Nc+wGyEyy5oK07g8ohoGO191YuQacmq1G2zmNidNFPkBtx0/UqARSvQzxJBA07yaJa1W2eKM32arm0jnSL34+23vkGBJfS52GezYQ2XPhBw9Y9x1jHfsMffIOK33qABali6LI/8AvvKV4KBOfr25p2qb4YcCEa29naD9i9HFc07sX3+2HAzGJbJUEK2XqZ5W6xmA3mjVPfoiErUJkMHYRHItvKbM+4gfwFw6UfCQsy7NMgD6Mdx+39iP8cAdoYNLh6cCFXkPEamyu/6uoIMeDNMrQM8O0/P5j7JTvUoGTCbRGVUZA3Raphwi88rN1n0XPjiLxCpmywBQRlk="

install:
  - source ci/travis/install.sh
  - conda config --add channels amacd31

script:
  - conda build conda.recipe
  - anaconda --token $CONDA_TOKEN upload `python ci/get_labels.py` `conda build --output conda.recipe`
