package:
    name: "hydromath"
    version: {{ environ['GIT_DESCRIBE_TAG'][1:] }}
build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
source:
    git_url: ../
requirements:
    build:
        - python x.x
        - libhydromath >=0.3.1  # [unix]
        - cffi
    run:
        - python x.x
        - numpy
        - libhydromath >=0.3.1  # [unix]
        - cffi
