package:
    name: "hydromath"
    version: {{ environ['GIT_DESCRIBE_TAG'][1:] }}
build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
source:
    git_url: https://github.com/amacd31/hydromath_py.git
    git_rev: master
requirements:
    build:
        - python x.x
        - libhydromath   # [unix]
        - cffi
    run:
        - python x.x
        - libhydromath   # [unix]
        - cffi
